<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bel</string>
	</array>
	<key>name</key>
	<string>Beluga</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(and|case|FN|fn|mlam|of|in|let|else|module|ttrue|ffalse|schema|some|block|impossible|Bool|then|struct)\b</string>
			<key>name</key>
			<string>keyword.control.bel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(type|rec|\|\-)\b</string>
			<key>name</key>
			<string>storage.type.bel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(-)?[0-9.]+\b</string>
			<key>name</key>
			<string>constant.numeric.bel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\=\&gt;|\|\s|\;|\=|\.|\:|\:\:|-\&gt;|\&lt;-)</string>
			<key>name</key>
			<string>keyword.other.bel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>%\{</string>
			<key>end</key>
			<string>\}%</string>
			<key>name</key>
			<string>comment.block.bel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>%</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.bel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>rec</string>
			<key>end</key>
			<string>\;</string>
			<key>name</key>
			<string>function.environment.bel</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.bel</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.colon.bel</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*([a-zA-Z0-9_'@!-^&amp;+=~]*[a-zA-Z0-9_'@#!-^&amp;+=~]*|\([|!%$+\-.,=&lt;/&gt;]+\))\s*(:)</string>
					<key>name</key>
					<string>function.declaration.bel</string>
				</dict>
				<dict>
					<key>name</key>
					<string>function.box.bel</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.bel</string>
	<key>uuid</key>
	<string>34BC871E-0262-4167-8AA9-A59A4C063D09</string>
</dict>
</plist>
