#!/bin/sh

# release=./release
echo 'Version number is:'
echo
cat VERSION || ( echo "VERSION file doesn't exist; aborting release" ; exit 1 )
echo
sleep 2
release=./beluga-"`cat VERSION`"-"`date +%Y%m%d`"
echo 'Release directory name is:'
echo
echo '    '$release
echo
sleep 1
if [ -e $release ]; then
  echo Release directory "$release" already exists.
  exit 1
fi

mkdir $release

echo 'Copying files in root'
cp -a \
 INSTALL \
 OMakefile \
 OMakeroot \
 README \
 STYLE \
 TEST \
 TEST-LF \
 TEST-TWELF \
 TODO \
 $release

mkdir $release/bin

echo 'Copying src'
cp -a \
 src \
 $release

echo 'Copying tools'
cp -a \
 tools \
 $release

echo 'Copying examples examples-twelf'
cp -a \
 examples \
 examples-twelf \
 $release

cd $release
echo Deleting useless files:
useless="`find . -print | egrep '~|.DS_Store'`"
echo rm $useless
rm $useless

echo Copying $release to $release-sandbox
cd ..
cp -a $release $release-sandbox

cd $release-sandbox
echo Running omake
omake || ( echo 'omake failed; aborting release' ; exit 1 )

echo Running TEST
./TEST || ( echo 'TEST failed; aborting release' ; exit 1 )

echo 'TEST exit value 0; check output for signs of trouble'
sleep 2
cd ..
echo 'Leaving '$release-sandbox' around if you want to test further'
sleep 1
echo 'Building archive' $release.tar
tar zcf $release.tar.gz $release || ( echo 'tar failed' ; exit 1 )
echo
ls -l $release.tar.gz
echo
