#!/bin/sh

# TEST-C: tests Beluga coverage
#
# Usage: TEST-C [options]
#
# [options], if given, are passed to Beluga.
# Example: TEST-C +d


# set $BELUGA to an absolute path to the toplevel .../beluga directory
#
pwd=`pwd`
BELUGA=`dirname $pwd/$0`
cd $BELUGA
BELUGA=`pwd`
# echo BELUGA: $BELUGA

# set $INTERPRETER to the executable
INTERPRETER=$BELUGA/bin/interpreter 

# set $X to the `beluga' examples directory
X=$BELUGA/examples
cd $X


# The following contain nonexhaustive cases, and are, correctly, rejected

echo 'interesting(?) nonexhaustive cases: '
$INTERPRETER +warncover $* \
    count-var/cntvar-crec.bel  \
    count-var/cntvar-explicit.bel \
    count-var/cntvar-simple.bel \
    count-var/cntvar-simple-crec.bel \
    count-var/cntvar-2.bel \
    free-vars/fvnat.bel \
    free-vars/fvnat-crec.bel \
    freshML/cps.bel \
    freshML/cps-crec.bel \
    freshML/cps-popl-tutorial1.bel \
    freshML/cps-popl-tutorial1-crec.bel \
    freshML/cps-popl-tutorial2.bel \
    freshML/cps-popl-tutorial2-crec.bel  \
    freshML/term-crec.bel \
    test/schema.bel \
    test/cross.bel \
    mini-ml/eval-sub.bel \
    mini-ml/eval-sub-explicit.bel \
    typed-eval/tpeval.bel \
    typed-eval/tpeval-explicit.bel \
    typed-eval/tpeval2.bel

sleep 2
echo

echo BROKEN: \
    lp-horn/sources.cfg \
    lp-horn/test-crec.cfg

sleep 2
echo

# The following don't cover for unknown reasons
$INTERPRETER +coverage $* \
    path/path-typed.bel \
    church-rosser/test.cfg \
    church-rosser/test-crec.cfg \
    compile/debruijn/test.cfg \
    cut-elim-crec.bel \
    free-vars/fvnat-explicit.bel \
    small-step/system-f.bel \
    small-step/system-f-iso.bel \
    test/id.bel \
    test/id-explicit.bel \
    tpcert.bel \
    ../examples-twelf/church-rosser/test.cfg \
    ../examples-twelf/compile/cls/test.cfg

echo 'Pausing after uninvestigated examples...'
sleep 2
echo 'continuing'
sleep 1

# The following use context matching, and are currently (incompletely) rejected
echo 'would be rejected (context matching):'
echo $INTERPRETER +coverage $* \
    freshML/debruijn-1.bel

echo OK:
$INTERPRETER +coverage $* \
    path/path.bel \
    test/alpha.bel \
    test/case1.bel \
    test/case1-explicit.bel \
    test/case2.bel \
    test/case2-explicit.bel \
    test/id-simple.bel \
    test/implicit-obj.bel \
    test/sigma3.bel \
    test/test-simple-explicit.bel \
    mini-ml/eval-sub-1.bel \
    mini-ml/eval-sub-1-explicit.bel \
    mini-ml/tps.bel \
    mini-ml/vsound.bel \
    mini-ml/vsound-explicit.bel \
    arith/arith.bel \
    compile/cls/sources.cfg \
    compile/cls/test.cfg \
    compile/cpm/sources.cfg \
    compile/cpm/test.cfg \
    compile/cps/sources.cfg \
    compile/cxm/sources.cfg \
    compile/debruijn/sources.cfg \
    compile/debruijn1/test.cfg \
    compile/debruijn1/sources.cfg \
    copy/copy.bel \
    copy/copy-crec.bel \
    copy/copy-explicit.bel \
    copy/copy-simple.bel \
    copy/copy-simple-crec.bel \
    copy/copy-simple-explicit.bel \
    count-var/cntvar.bel \
    cut-elim.bel \
    debruijn1/sources.cfg \
    equal/eq-proof-tuple.bel \
    equal/eq-proof.bel \
    equal/eq-proof-full-crec.bel \
    fol/sources.cfg \
    fol/test.cfg \
    freshML/cconv-cheney.bel \
    freshML/conv-untyped.bel \
    freshML/term.bel \
    small-step/lam.bel \
    subject-red.bel \
    subject-red-crec.bel \
    test/backarrow.bel \
    test/dependency.bel \
    test/test.bel \
    test/test-simple.bel \
    unique/unique.bel \
    unique/unique-crec.bel \
    unique/unique-eval.bel \
    LF/arith.lf \
    LF/arith-rec1.lf \
    LF/lambda.lf \
    LF/lambda-rec.lf \
    LF/simple-typing.lf \
    LF/lam-tp-rec.lf \
    LF/cut-elim.lf \
    LF/kindtest.lf \
    LF/mini-ml.lf \
    LF/mini-ml-rec.lf \
    LF/vsound.lf \
    LF/vsound-rec.lf \
    LF/tpeval.lf \
    LF/tpeval-rec.lf \
    LF/tpcert.lf \
    LF/tps.lf \
    test/sigma1.bel \
    test/sigma2.bel \
    test/sigma4.bel \
    ../examples-twelf/arith/sources.cfg \
    ../examples-twelf/alloc-sem/sources.cfg \
    ../examples-twelf/ccc/sources.cfg \
    ../examples-twelf/church-rosser/sources.cfg \
    ../examples-twelf/cpsocc/sources.cfg \
    ../examples-twelf/compile/cls/sources.cfg \
    ../examples-twelf/compile/debruijn/sources.cfg \
    ../examples-twelf/compile/debruijn1/sources.cfg \
    ../examples-twelf/compile/cps/sources.cfg \
    ../examples-twelf/compile/cpm/sources.cfg \
    ../examples-twelf/compile/cpm/test.cfg \
    ../examples-twelf/cut-elim/sources.cfg \
    ../examples-twelf/fol/sources.cfg \
    ../examples-twelf/handbook/sources.cfg \
    ../examples-twelf/kolm/sources.cfg \
    ../examples-twelf/lp/sources.cfg \
    ../examples-twelf/lp-horn/sources.cfg \
    ../examples-twelf/mini-ml/sources.cfg \
    ../examples-twelf/mini-ml/test.cfg \
    ../examples-twelf/prop-calc/sources.cfg

exit 0


# ignore the following

for file in  \
do
  $INTERPRETER +coverage $file
  R=$?
  echo STATUS=$R
  B=$B$R
done

echo
echo $B
# $INTERPRETER +coverage $*
