#!/bin/bash

usage() {
    echo "Usage: $0 [test-options] -- [beluga-options]"
    echo
    echo "Synopsis: test harness for Beluga."
    echo
    echo "Notes:"
    echo "    - Pure LF signatures are in files sources.cfg."
    echo "    - Proofs written in Beluga are in test.cfg."
    echo "    - Files ending in .bel contain Beluga programs."
    echo "    - If a test.cfg file is found in a subdirectory, only it will be tested."
    echo "    - If no test.cfg file is found, all .bel files in the subdirectory"
    echo "      will be tested."
    echo "    - To inhibit testing .bel files, put an empty test.cfg in that directory."
}

echo "Parameters for this run (override as necessary using environment variables):"
echo

# Path to the Beluga source distribution.
echo -e "\t" BELUGADIR=${BELUGADIR:=$(dirname $0)}

# Set $EXE to the executable to test.
echo -e "\t" EXE=${EXE:=$BELUGADIR/bin/interpreter}

# Test scripts.
echo -e "\t" TESTDIR=${TESTDIR:=$BELUGADIR/examples}

echo

# Find test cases.
test_cases() {
    for dir in $(find $TESTDIR -type d)
    do
	[[ -f $dir/sources.cfg ]] && echo $dir/sources.cfg
	if [[ -f $dir/test.cfg ]]
	then
	    echo $dir/test.cfg
	else
	    find $dir/ -maxdepth 1 -name '*.bel' -type f
	fi
    done
}

for i in $(test_cases)
do
    echo "TEST CASE: $i"
    $EXE -noprint $* $i
done
